Added deeplink info (MIT-1850)
omise/omise-ios pull request #231
Opened 2023-10-14 06:28 UTC by muthuswamyopn

2023-10-16 06:51 UTC, danfowler requested changes

2023-10-16 06:51 UTC, danfowler commented on README.md
> +[Opn Payments](https://www.omise.co/) is a payment service provider operating
```suggestion
[Opn Payments](https://docs.opn.ooo/) is a payment service provider operating
```

2023-10-16 06:51 UTC, danfowler commented on README.md
> +[tokenizing credit cards](https://www..co/tokens-api) and
```suggestion
[tokenizing credit cards](https://docs.opn.ooo/tokens-api) and
```

2023-10-16 06:51 UTC, danfowler commented on README.md
> +MIT [See the full license text](https://github.com//-ios/blob/master/LICENSE)
```suggestion
MIT [See the full license text](https://github.com/omise/omise-ios/blob/master/LICENSE)
```

2023-10-16 06:51 UTC, danfowler commented on README.md
> +Some payment methods require the customers to authorize the payment via an authorized URL. This includes the [3-D Secure verification](https://www.omise.co/fraud-protection#3-d-secure), [Internet Ban
```suggestion
Some payment methods require the customers to authorize the payment via an authorized URL. This includes the [3-D Secure verification](https://docs.opn.ooo/fraud-protection#3-d-secure), [Internet Banking payment](https://docs.opn.ooo/offsite-payment), [Alipay](https://docs.opn.ooo/alipay). The Opn Payments iOS SDK provides a built-in class to do the authorization.
```

2023-10-27 06:40 UTC, muthuswamyopn commented on README.md
> +[![](https://cdn.omise.co/assets/omise.png)](https://omise.co)
I am not sure where the CDN for Opn is. I tried cdn.opn.ooo and cd.docs.opn.ooo but they do not resolve. I will ask marketing where the logo is.

I have changed links to docs.opn.ooo, except for github - which is still github.com/omise/....

Also should support email change to support@opn.ooo?

2023-10-27 07:08 UTC, danfowler commented on README.md
> +[![](https://cdn.omise.co/assets/omise.png)](https://omise.co)
> I am not sure where the CDN for Opn is. I tried cdn.opn.ooo and cd.docs.opn.ooo but they do not resolve. I will ask marketing where the logo is.

OK

> I have changed links to docs.opn.ooo, except for github - which is still github.com/omise/....

good

> Also should support email change to [support@opn.ooo](mailto:support@opn.ooo)?

yes

2023-10-27 09:13 UTC, muthuswamyopn commented on README.md
> +[![](https://cdn.omise.co/assets/omise.png)](https://omise.co)
Done.

2023-10-27 10:14 UTC, danfowler commented on README.md
> +[![](https://cdn.omise.co/assets/omise.png)](https://omise.co)
In the interests of simplifying, I'm inclined to just remove the image to align with our other public repos.

2023-10-27 10:15 UTC, danfowler commented on README.md
> +[![](https://cdn.omise.co/assets/omise.png)](https://opn.ooo)
```suggestion
```

2023-10-27 10:28 UTC, muthuswamyopn commented
Fine Dan

2023-10-30 08:39 UTC, danfowler approved these changes

2023-10-31 07:36 UTC, vault087 approved these changes

2023-10-31 07:36 UTC, merged